package com.cherrypicks.tcc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Campaign implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Double stampRatio;

	public Campaign() {
	}

	public java.lang.Double getStampRatio() {
		return this.stampRatio;
	}

	public void setStampRatio(java.lang.Double stampRatio) {
		this.stampRatio = stampRatio;
	}

	public Campaign(java.lang.Double stampRatio) {
		this.stampRatio = stampRatio;
	}

}