package com.cherrypicks.tcc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PosOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String externalStoreId;
	private java.lang.String transDateTime;
	private java.lang.String transNo;
	private java.lang.Double transAmt;
	private java.lang.String currency;
	private java.lang.String collectCode;

	public PosOrder() {
	}

	public java.lang.String getExternalStoreId() {
		return this.externalStoreId;
	}

	public void setExternalStoreId(java.lang.String externalStoreId) {
		this.externalStoreId = externalStoreId;
	}

	public java.lang.String getTransDateTime() {
		return this.transDateTime;
	}

	public void setTransDateTime(java.lang.String transDateTime) {
		this.transDateTime = transDateTime;
	}

	public java.lang.String getTransNo() {
		return this.transNo;
	}

	public void setTransNo(java.lang.String transNo) {
		this.transNo = transNo;
	}

	public java.lang.Double getTransAmt() {
		return this.transAmt;
	}

	public void setTransAmt(java.lang.Double transAmt) {
		this.transAmt = transAmt;
	}

	public java.lang.String getCurrency() {
		return this.currency;
	}

	public void setCurrency(java.lang.String currency) {
		this.currency = currency;
	}

	public java.lang.String getCollectCode() {
		return this.collectCode;
	}

	public void setCollectCode(java.lang.String collectCode) {
		this.collectCode = collectCode;
	}

	public PosOrder(java.lang.String externalStoreId,
			java.lang.String transDateTime, java.lang.String transNo,
			java.lang.Double transAmt, java.lang.String currency,
			java.lang.String collectCode) {
		this.externalStoreId = externalStoreId;
		this.transDateTime = transDateTime;
		this.transNo = transNo;
		this.transAmt = transAmt;
		this.currency = currency;
		this.collectCode = collectCode;
	}

}