package com.cherrypicks.tcc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PosPaymentInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String paymentMethod;
	private java.lang.String customerId;
	private java.lang.String loyaltyCardNum;

	public PosPaymentInfo() {
	}

	public java.lang.String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(java.lang.String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getLoyaltyCardNum() {
		return this.loyaltyCardNum;
	}

	public void setLoyaltyCardNum(java.lang.String loyaltyCardNum) {
		this.loyaltyCardNum = loyaltyCardNum;
	}

	public PosPaymentInfo(java.lang.String paymentMethod,
			java.lang.String customerId, java.lang.String loyaltyCardNum) {
		this.paymentMethod = paymentMethod;
		this.customerId = customerId;
		this.loyaltyCardNum = loyaltyCardNum;
	}

}