package com.cherrypicks.tcc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PosRedeemCode implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String redeemCode;
	private int qty;

	public PosRedeemCode() {
	}

	public java.lang.String getRedeemCode() {
		return this.redeemCode;
	}

	public void setRedeemCode(java.lang.String redeemCode) {
		this.redeemCode = redeemCode;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public PosRedeemCode(java.lang.String redeemCode, int qty) {
		this.redeemCode = redeemCode;
		this.qty = qty;
	}

}