package com.cherrypicks.tcc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductGroup implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Double totalQty;
	private Double totalAmt;
	private java.lang.String groupName;

	public ProductGroup() {
	}

	public java.lang.String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(java.lang.String groupName) {
		this.groupName = groupName;
	}

	public java.lang.Double getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(java.lang.Double totalAmt) {
		this.totalAmt = totalAmt;
	}

	public java.lang.Double getTotalQty() {
		return this.totalQty;
	}

	public void setTotalQty(java.lang.Double totalQty) {
		this.totalQty = totalQty;
	}

	public ProductGroup(java.lang.Double totalQty, java.lang.Double totalAmt,
			java.lang.String groupName) {
		this.totalQty = totalQty;
		this.totalAmt = totalAmt;
		this.groupName = groupName;
	}

}