package com.cherrypicks.tcc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleResult implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RuleResult() {
    }

    private String uniqueCode;
	private long stamp;
	private long point;

	public String getUniqueCode() {
		return uniqueCode;
	}

	public void setUniqueCode(String uniqueCode) {
		this.uniqueCode = uniqueCode;
	}

	public long getStamp() {
		return stamp;
	}

	public void setStamp(long stamp) {
		this.stamp = stamp;
	}

	public long getPoint() {
		return point;
	}

	public void setPoint(long point) {
		this.point = point;
	}

}