package com.cherrypicks.tcc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StampRatio implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer ratio;

	public StampRatio() {
	}

	public java.lang.Integer getRatio() {
		return this.ratio;
	}

	public void setRatio(java.lang.Integer ratio) {
		this.ratio = ratio;
	}

	public StampRatio(java.lang.Integer ratio) {
		this.ratio = ratio;
	}

}